#ifndef TILE_PARSER
#define TILE_PARSER

#include <filesystem>
#include <vector>
#include <map>
#include "tile.hpp"
#include "rule_set.hpp"
#include "raw_tile_data.hpp"

namespace fs = std::filesystem;

class TileParser{
    public:
        TileParser(fs::path image, fs::path config);
        // Gets the tiles generated by the parser, errors if not set up yet and called
        std::vector<Tile*> get_tiles();
        TileRuleSet* get_rule_set();
    private:
        Image* _rule_image;
        // The series of completed tiles from 0 to T - 1
        std::vector<Tile*> tiles;
        // Parses the configure file and sets up the _tile_x_count and _tile_y_count, then calculates the size of each tile based on the image size (Cuts off excess);
        void parse_config(fs::path config_path);
        int _tile_x_count = -1;
        int _tile_y_count = -1;
        int _tile_x_size;
        int _tile_y_size;
        int _tile_c_size;
        int current_id = 0;
        // A calculated sized of the tiles for a given image (tile_x % img_size_x * tile_y % img_size_y), an ID representation of the images, from 0 to T
        int* _id_grid;
        // A map of color data for easy lookup and to check if a tile already exists.
        std::map<double, raw_tile_data*> _data_map;
        // If it doesn't exist, add it to the vector, if it does check the id and add it to the id grid.
        std::vector<raw_tile_data*> _raw_tiles;
        // Chop up image and parse color data, assigning IDs to a grid as we go
        void parse_tiles();
        // Gets the tile data for a given set tile
        raw_tile_data* get_tile_data(int x_offset, int y_offset);
        // Uses the _id_grid that was generated by parse_tiles() to determine what the rule sets are
        // TODO: ONCE THIS IS DONE, DELETE _id_grid!!!
        void set_ruleset();
        // gets the id at a given set
        int id_at(int x, int y);
        // A T * 4 * T Matrix of all the rules set by the set_ruleset function and passes to each raw data tile
        TileRuleSet* _master_ruleset;
        // Iterates though raw tiles and ruleset and assembles _tiles
        void generate_tiles();
};

#endif